services:
  - type: web
    name: myapi
    runtime: docker
    dockerfilePath: MyApi/Dockerfile
    dockerContext: .
    plan: basic-256mb
    rootDir: .
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString

databases:
  - name: mydb
